### ISSUE TITLE
How can I make the pages sorted by date and time?

### ISSUE THREAD

**Issue by khanduras** [PhileCMS/Phile-Blog-Theme#4]
I want to have two separate meta headings: date and time.
How can I get posts sorted so that newest posts appear first?

**Comment by Schlaefer** [comment]
Add two tags to the pages:

```
<!--
…
Date: 2018-03-23
Time: 10:00
-->
```

Then set the page order. For example to sort for date first and time second:

```
$config['pages_order'] = 'meta.date:desc meta.time:desc';
```

**Comment by khanduras** [comment]
3 years later, better late than never.
